=== ONSdigital/ons-schema-definitions/schemas/launch_v2.json
{
  "$id": "launch_v2.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ONS EQ Launch Schema v2",
  "type": "object",
  "properties": {
    "account_service_url": {
      "$ref": "common/definitions.json#/account_service_url"
    },
    "case_id": {
      "$ref": "common/definitions.json#/case_id"
    },
    "channel": {
      "$ref": "common/definitions.json#/channel"
    },
    "collection_exercise_sid": {
      "$ref": "common/definitions.json#/collection_exercise_sid"
    },
    "exp": {
      "description": "JWT Issued At claim, see https://tools.ietf.org/html/rfc7519#section-4.1",
      "type": "integer"
    },
    "iat": {
      "description": "JWT Expiration Time claim, see https://tools.ietf.org/html/rfc7519#section-4.1",
      "type": "integer"
    },
    "jti": {
      "$ref": "common/definitions.json#/jti"
    },
    "language_code": {
      "$ref": "common/definitions.json#/launch_language_code"
    },
    "region_code": {
      "$ref": "common/definitions.json#/region_code"
    },
    "response_expires_at": {
      "$ref": "common/definitions.json#/response_expires_at"
    },
    "response_id": {
      "$ref": "common/definitions.json#/response_id"
    },
    "schema_name": {
      "$ref": "common/definitions.json#/schema_name"
    },
    "schema_url": {
      "$ref": "common/definitions.json#/schema_url"
    },
    "survey_metadata": {
      "$ref": "common/survey_metadata.json#/survey_metadata"
    },
    "tx_id": {
      "$ref": "common/definitions.json#/tx_id"
    },
    "version": {
      "$ref": "common/definitions.json#/payload_version_v2"
    }
  },
  "required": [
    "exp",
    "iat",
    "jti",
    "tx_id",
    "version",
    "account_service_url",
    "case_id",
    "collection_exercise_sid",
    "response_id"
  ],
  "additionalProperties": false,
  "oneOf": [
    {
      "required": ["schema_name"]
    },
    {
      "required": ["schema_url"]
    }
  ]
}

=== ONSdigital/ons-schema-definitions/examples/rm_to_eq_runner/payload_v2/launch_jwt_business.json
{
  "exp": 1684501576,
  "iat": 1684501276,
  "jti": "47c97acf-ebc2-46bc-b2d0-75e2fcf3ad33",
  "tx_id": "c44c7942-9956-421e-80d4-c4fa813e13b4",
  "version": "v2",
  "account_service_url": "https://upstream.example.com/surveys/todo",
  "case_id": "c3756c53-28ee-41a4-a382-2dd4f50edf94",
  "collection_exercise_sid": "b5458b19-8a4e-43ad-8ead-60e900441615",
  "response_id": "49900000001Fb5458b19-8a4e-43ad-8ead-60e90044161520001",
  "response_expires_at": "2023-05-23T07:00:00+01:00",
  "schema_name": "2_0001",
  "survey_metadata": {
    "data": {
      "case_ref": "1000000000000007",
      "form_type": "0001",
      "period_id": "1912",
      "period_str": "December",
      "ref_p_end_date": "2023-05-18",
      "ref_p_start_date": "2023-05-23",
      "ru_name": " RUNAME1_COMPANY1 RUNNAME2_COMPANY1",
      "ru_ref": "49900000001F",
      "trad_as": "TOTAL UK ACTIVITY  ",
      "user_id": "855a454c-c6d8-4fcb-94c6-26a4b9732b42",
      "survey_id": "139",
      "employment_date": "2023-05-18",
      "sds_dataset_id": "c067f6de-6d64-42b1-8b02-431a3486c178"
    }
  }
}

=== ONSdigital/ons-schema-definitions/examples/rm_to_eq_runner/payload_v2/launch_jwt_social.json
{
  "exp": 1458057712,
  "iat": 1458047712,
  "jti": "6b383088-b8f8-4167-8847-c4aaeda8fe16",
  "tx_id": "0f534ffc-9442-414c-b39f-a756b4adc6cb",
  "version": "v2",
  "account_service_url": "https://upstream.example.com",
  "case_id": "628256cf-5c78-4896-8bec-f0ddb69aaa11",
  "channel": "RH",
  "collection_exercise_sid": "9ced8dc9-f2f3-49f3-95af-2f3ca0b74ee3",
  "region_code": "GB-WLS",
  "response_expires_at": "2022-12-01T00:00:00+00:00",
  "response_id": "QzXMrPqoLiyEyerrED88AbkQoQK0sVVX72ZtVphHr0w=",
  "schema_name": "adhoc_0001",
  "survey_metadata": {
    "data": {
      "case_ref": "1000000000000001",
      "qid": "0130000000000300",
      "BLOOD_TEST_BARCODE": "BLT11111111",
      "SWAB_TEST_BARCODE": "swT11111111",
      "PARTICIPANT_ID": "DHRF-123456789012",
      "TEST_QUESTIONS": "F",
      "COLLEX_OPEN_DATE": "08 Jan 2023",
      "COLLEX_CLOSE_DATE": "28 Jan 2023",
      "FIRST_NAME": "Vinny",
      "WINDOW_START_DATE": "2023-01-08",
      "WINDOW_CLOSE_DATE": "2023-01-28",
      "PORTAL_ID": "1234567",
      "PARTICIPANT_WINDOW_ID": "DHRF-123456789012-001"
    },
    "receipting_keys": ["qid"]
  }
}

=== ONSdigital/ons-schema-definitions/examples/payload_v2/rm_to_eq_runner/launch_jwt_social.json
{
    "exp": 1458057712,
    "iat": 1458047712,
    "jti": "6b383088-b8f8-4167-8847-c4aaeda8fe16",
    "tx_id": "0f534ffc-9442-414c-b39f-a756b4adc6cb",
    "version": "v2",
    "account_service_url": "https://upstream.example.com",
    "case_id": "628256cf-5c78-4896-8bec-f0ddb69aaa11",
    "channel": "RH",
    "collection_exercise_sid": "789",
    "region_code": "GB-WLS",
    "response_expires_at": "2022-12-01T00:00:00+00:00",
    "response_id": "QzXMrPqoLiyEyerrED88AbkQoQK0sVVX72ZtVphHr0w=",
    "schema_name": "adhoc_0001",
    "survey_metadata": {
        "data": {
            "case_ref": "1000000000000001",
            "case_type": "B",
            "questionnaire_id": "bdf7dff2-1d73-4b97-bd2d-91f2e53160b9"
        },
        "receipting_keys": ["questionnaire_id"]
    }
}
