=== ONSdigital/ons-schema-definitions/schemas/submission_v1.json
{
  "$id": "submission_v1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "ONS EQ Submission Schema v1",
  "properties": {
    "case_id": {
      "$ref": "common/definitions.json#/case_id"
    },
    "case_ref": {
      "$ref": "common/definitions.json#/case_ref"
    },
    "case_type": {
      "$ref": "common/definitions.json#/case_type"
    },
    "channel": {
      "$ref": "common/definitions.json#/channel"
    },
    "collection": {
      "additionalProperties": false,
      "properties": {
        "exercise_sid": {
          "$ref": "common/definitions.json#/collection_exercise_sid"
        },
        "instrument_id": {
          "$ref": "common/definitions.json#/form_type"
        },
        "period": {
          "$ref": "common/definitions.json#/period_id"
        },
        "schema_name": {
          "$ref": "common/definitions.json#/schema_name"
        }
      },
      "required": ["exercise_sid", "period", "instrument_id"],
      "type": "object"
    },
    "data": {
      "description": "This is conditionally defined in the schemas below."
    },
    "flushed": {
      "$ref": "common/definitions.json#/flushed"
    },
    "form_type": {
      "$ref": "common/definitions.json#/form_type"
    },
    "launch_language_code": {
      "$ref": "common/definitions.json#/launch_language_code"
    },
    "metadata": {
      "additionalProperties": true,
      "properties": {
        "display_address": {
          "type": "string"
        },
        "ref_period_end_date": {
          "$ref": "common/definitions.json#/ref_p_end_date"
        },
        "ref_period_start_date": {
          "$ref": "common/definitions.json#/ref_p_start_date"
        },
        "ru_ref": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        }
      },
      "required": ["user_id", "ru_ref"],
      "type": "object"
    },
    "origin": {
      "$ref": "common/definitions.json#/origin"
    },
    "region_code": {
      "$ref": "common/definitions.json#/region_code"
    },
    "started_at": {
      "$ref": "common/definitions.json#/started_at"
    },
    "submission_language_code": {
      "$ref": "common/definitions.json#/submission_language_code"
    },
    "submitted_at": {
      "$ref": "common/definitions.json#/submitted_at"
    },
    "survey_id": {
      "$ref": "common/definitions.json#/survey_id"
    },
    "tx_id": {
      "$ref": "common/definitions.json#/tx_id"
    },
    "type": {
      "$ref": "common/definitions.json#/submission_type"
    },
    "version": {
      "$ref": "common/definitions.json#/data_version"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "allOf": [
    {
      "if": {
        "properties": { "type": { "const": "uk.gov.ons.edc.eq:feedback" } }
      },
      "then": {
        "properties": {
          "data": {
            "oneOf": [
              { "$ref": "common/response_data.json#/feedback_response" },
              { "$ref": "common/response_data.json#/feedback_response_legacy" }
            ]
          }
        }
      },
      "else": {
        "if": {
          "properties": { "version": { "const": "0.0.3" } }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "common/response_data.json#/survey_response_0_0_3"
            }
          }
        },
        "else": {
          "properties": {
            "data": {
              "$ref": "common/response_data.json#/survey_response_0_0_1"
            }
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "type": { "const": "uk.gov.ons.edc.eq:surveyresponse" }
        }
      },
      "then": {
        "description": "These properties are required for survey responses but not for survey feedback.",
        "required": ["case_id", "flushed"]
      }
    }
  ],
  "required": [
    "tx_id",
    "type",
    "version",
    "origin",
    "survey_id",
    "submitted_at",
    "collection",
    "metadata",
    "data"
  ]
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v1/surveyresponse_0_0_3.json
{
  "tx_id": "a8e1d41d-728c-47c4-89b2-2d087e6e01a4",
  "type": "uk.gov.ons.edc.eq:surveyresponse",
  "version": "0.0.3",
  "origin": "uk.gov.ons.edc.eq",
  "survey_id": "0",
  "flushed": false,
  "submitted_at": "2019-08-20T11:05:44.541979",
  "form_type": "0234",
  "case_type": "B",
  "case_ref": "1000000000000001",
  "channel": "EQ",
  "collection": {
    "exercise_sid": "ae62cb63-be41-4160-8bff-eb2a3bab5c6e",
    "schema_name": "test_relationships",
    "period": "201605",
    "instrument_id": "0123"
  },
  "metadata": {
    "user_id": "UNKNOWN",
    "ru_ref": "74117071486i",
    "display_address": "1 Road, Town City"
  },
  "launch_language_code": "en",
  "submission_language_code": "cy",
  "region_code": "GB-ENG",
  "started_at": "2019-08-20T11:05:25.604330",
  "case_id": "6453e4d3-aac1-424c-be28-23c57aa9e17d",
  "data": {
    "answers": [
      {
        "answer_id": "first-name",
        "value": "John",
        "list_item_id": "zGBdpb"
      },
      {
        "answer_id": "last-name",
        "value": "Doe",
        "list_item_id": "zGBdpb"
      },
      {
        "answer_id": "first-name",
        "value": "Marie",
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "last-name",
        "value": "Doe",
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "anyone-else",
        "value": "No"
      },
      {
        "answer_id": "number-of-bedrooms-answer",
        "value": 4
      },
      {
        "answer_id": "date-of-birth-answer",
        "value": "1990-01-01",
        "list_item_id": "EINoLs"
      },
      {
        "answer_id": "internet-answer",
        "value": [
          "Broadband or WiFi",
          "A mobile phone network such as 3G, 4G or 5G",
          "Public WiFi hotspot"
        ]
      },
      {
        "answer_id": "business-type-answer",
        "value": "Enter Business type here!",
        "list_item_id": "EINoLs"
      },
      {
        "answer_id": "relationship-answer",
        "value": [
          {
            "list_item_id": "zGBdpb",
            "to_list_item_id": "cWGwcF",
            "relationship": "Husband or Wife"
          },
          {
            "list_item_id": "nEMpwe",
            "to_list_item_id": "adNCSi",
            "relationship": "Son or daughter"
          },
          {
            "list_item_id": "ukGiCK",
            "to_list_item_id": "adNCSi",
            "relationship": "Mother or father"
          }
        ]
      },
      {
        "answer_id": "other-address-uk-answer",
        "value": {
          "line1": "Address Line 1",
          "town": "Town",
          "postcode": "NP10 8XG",
          "uprn": "12345678912"
        },
        "list_item_id": "cWGwcF"
      }
    ],
    "lists": [
      {
        "items": ["zGBdpb", "cWGwcF"],
        "name": "people"
      }
    ]
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v1/feedback_0_0_3.json
{
  "origin": "uk.gov.ons.edc.eq",
  "submitted_at": "2021-10-12T10:41:23+00:00",
  "survey_id": "001",
  "tx_id": "5d4e1a37-ed21-440a-8c4d-3054a124a104",
  "type": "uk.gov.ons.edc.eq:feedback",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "version": "0.0.3",
  "flushed": false,
  "started_at": "2021-10-12T10:41:23+00:00",
  "case_id": "6453e4d3-aac1-424c-be28-23c57aa9e17d",
  "form_type": "0234",
  "case_type": "B",
  "case_ref": "1000000000000001",
  "channel": "EQ",
  "region_code": "GB-ENG",
  "collection": {
    "exercise_sid": "eedbdf46-adac-49f7-b4c3-2251807381c3",
    "schema_name": "carbon_0007",
    "period": "3003",
    "instrument_id": "0123"
  },
  "metadata": {
    "ref_period_end_date": "2021-03-29",
    "ref_period_start_date": "2021-03-01",
    "ru_ref": "11110000022H",
    "user_id": "d98d78eb-d23a-494d-b67c-e770399de383"
  },
  "data": {
    "feedback_text": "Page design feedback",
    "feedback_type": "Page design and structure",
    "feedback_count": "7"
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v1/surveyresponse_0_0_1.json
{
  "tx_id": "a8e1d41d-728c-47c4-89b2-2d087e6e01a4",
  "type": "uk.gov.ons.edc.eq:surveyresponse",
  "version": "0.0.1",
  "origin": "uk.gov.ons.edc.eq",
  "survey_id": "0",
  "flushed": false,
  "submitted_at": "2019-08-20T11:05:44.541979",
  "launch_language_code": "en",
  "submission_language_code": "cy",
  "region_code": "GB-ENG",
  "started_at": "2019-08-20T11:05:25.604330",
  "form_type": "0234",
  "case_id": "6453e4d3-aac1-424c-be28-23c57aa9e17d",
  "case_type": "B",
  "case_ref": "1000000000000001",
  "channel": "EQ",
  "collection": {
    "exercise_sid": "ae62cb63-be41-4160-8bff-eb2a3bab5c6e",
    "schema_name": "test_relationships",
    "period": "201605",
    "instrument_id": "0234"
  },
  "metadata": {
    "user_id": "UNKNOWN",
    "ru_ref": "74117071486i",
    "display_address": "1 Road, Town City",
    "ref_period_start_date": "2019-07-01",
    "ref_period_end_date": "2019-10-31"
  },
  "data": {
    "0001": "This is an answer to q_code 0001",
    "0002": "This is an answer to q_code 0002",
    "0003": "This is an answer to q_code 0003"
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v1/feedback_0_0_3_legacy.json
{
  "origin": "uk.gov.ons.edc.eq",
  "submitted_at": "2021-10-12T10:41:23+00:00",
  "survey_id": "001",
  "tx_id": "5d4e1a37-ed21-440a-8c4d-3054a124a104",
  "type": "uk.gov.ons.edc.eq:feedback",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "version": "0.0.3",
  "started_at": "2021-10-12T10:41:23+00:00",
  "form_type": "0234",
  "case_type": "B",
  "case_ref": "1000000000000001",
  "channel": "EQ",
  "region_code": "GB-ENG",
  "collection": {
    "exercise_sid": "eedbdf46-adac-49f7-b4c3-2251807381c3",
    "schema_name": "carbon_0007",
    "period": "3003",
    "instrument_id": "0123"
  },
  "metadata": {
    "ref_period_end_date": "2021-03-29",
    "ref_period_start_date": "2021-03-01",
    "ru_ref": "11110000022H",
    "user_id": "d98d78eb-d23a-494d-b67c-e770399de383"
  },
  "data": {
    "name": "John Doe",
    "email": "john.doe@example.com",
    "message": "Page design feedback",
    "url": "https://www.example.com/question-one"
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v1/feedback_0_0_1_legacy.json
{
  "origin": "uk.gov.ons.edc.eq",
  "submitted_at": "2021-10-12T10:41:23+00:00",
  "survey_id": "001",
  "tx_id": "5d4e1a37-ed21-440a-8c4d-3054a124a104",
  "type": "uk.gov.ons.edc.eq:feedback",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "version": "0.0.1",
  "started_at": "2021-10-12T10:41:23+00:00",
  "form_type": "0234",
  "case_type": "B",
  "case_ref": "1000000000000001",
  "channel": "EQ",
  "region_code": "GB-ENG",
  "collection": {
    "exercise_sid": "eedbdf46-adac-49f7-b4c3-2251807381c3",
    "schema_name": "carbon_0007",
    "period": "3003",
    "instrument_id": "0123"
  },
  "metadata": {
    "user_id": "UNKNOWN",
    "ru_ref": "74117071486i",
    "display_address": "1 Road, Town City",
    "ref_period_start_date": "2019-07-01",
    "ref_period_end_date": "2019-10-31"
  },
  "data": {
    "name": "John Doe",
    "email": "john.doe@example.com",
    "message": "Page design feedback"
  }
}
