=== ONSdigital/ons-schema-definitions/schemas/submission_v2.json
{
  "$id": "submission_v2.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "ONS EQ Submission Schema v2",
  "properties": {
    "case_id": {
      "$ref": "common/definitions.json#/case_id"
    },
    "channel": {
      "$ref": "common/definitions.json#/channel"
    },
    "collection_exercise_sid": {
      "$ref": "common/definitions.json#/collection_exercise_sid"
    },
    "data": {
      "description": "This is conditionally defined in the schemas below."
    },
    "data_version": {
      "$ref": "common/definitions.json#/data_version"
    },
    "flushed": {
      "$ref": "common/definitions.json#/flushed"
    },
    "launch_language_code": {
      "$ref": "common/definitions.json#/launch_language_code"
    },
    "origin": {
      "$ref": "common/definitions.json#/origin"
    },
    "region_code": {
      "$ref": "common/definitions.json#/region_code"
    },
    "schema_name": {
      "$ref": "common/definitions.json#/schema_name"
    },
    "schema_url": {
      "$ref": "common/definitions.json#/schema_url"
    },
    "started_at": {
      "$ref": "common/definitions.json#/started_at"
    },
    "submission_language_code": {
      "$ref": "common/definitions.json#/submission_language_code"
    },
    "submitted_at": {
      "$ref": "common/definitions.json#/submitted_at"
    },
    "survey_metadata": {
      "$ref": "common/survey_metadata.json#/submission_survey_metadata"
    },
    "tx_id": {
      "$ref": "common/definitions.json#/tx_id"
    },
    "type": {
      "$ref": "common/definitions.json#/submission_type"
    },
    "version": {
      "$ref": "common/definitions.json#/payload_version_v2"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "if": {
    "properties": { "type": { "const": "uk.gov.ons.edc.eq:feedback" } }
  },
  "then": {
    "properties": {
      "data": {
        "$ref": "common/response_data.json#/feedback_response"
      }
    }
  },
  "else": {
    "if": {
      "properties": { "data_version": { "const": "0.0.3" } }
    },
    "then": {
      "properties": {
        "data": {
          "$ref": "common/response_data.json#/survey_response_0_0_3"
        }
      }
    },
    "else": {
      "properties": {
        "data": {
          "$ref": "common/response_data.json#/survey_response_0_0_1"
        }
      }
    }
  },
  "required": [
    "tx_id",
    "type",
    "version",
    "data_version",
    "origin",
    "flushed",
    "submitted_at",
    "launch_language_code",
    "submission_language_code",
    "collection_exercise_sid",
    "case_id",
    "survey_metadata",
    "data"
  ],
  "oneOf": [
    {
      "required": ["schema_name"]
    },
    {
      "required": ["schema_url"]
    }
  ]
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v2/adhoc/feedback_0_0_1.json
{
  "tx_id": "ea82c224-0f80-41cc-b877-8a7804b56c26",
  "type": "uk.gov.ons.edc.eq:feedback",
  "version": "v2",
  "data_version": "0.0.1",
  "origin": "uk.gov.ons.edc.eq",
  "flushed": false,
  "submitted_at": "2016-05-21T16:37:56.551086",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "collection_exercise_sid": "9ced8dc9-f2f3-49f3-95af-2f3ca0b74ee3",
  "schema_name": "mbs_0001",
  "started_at": "2016-05-21T16:33:30.665144",
  "case_id": "a386b2de-a615-42c8-a0f4-e274f9eb28ee",
  "region_code": "GB-ENG",
  "channel": "RH",
  "survey_metadata": {
    "survey_id": "009",
    "case_ref": "1000000000000001",
    "questionnaire_id": "0130000000000300"
  },
  "data": {
    "feedback_text": "Page design feedback",
    "feedback_type": "Page design and structure",
    "feedback_count": "7"
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v2/adhoc/feedback_0_0_1_legacy.json
{
  "tx_id": "ea82c224-0f80-41cc-b877-8a7804b56c26",
  "type": "uk.gov.ons.edc.eq:feedback",
  "version": "v2",
  "data_version": "0.0.1",
  "origin": "uk.gov.ons.edc.eq",
  "flushed": false,
  "submitted_at": "2016-05-21T16:37:56.551086",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "collection_exercise_sid": "9ced8dc9-f2f3-49f3-95af-2f3ca0b74ee3",
  "schema_name": "mbs_0001",
  "started_at": "2016-05-21T16:33:30.665144",
  "case_id": "a386b2de-a615-42c8-a0f4-e274f9eb28ee",
  "region_code": "GB-ENG",
  "channel": "RH",
  "survey_metadata": {
    "survey_id": "009",
    "case_ref": "1000000000000001",
    "qid": "0130000000000300",
    "BLOOD_TEST_BARCODE": "BLT11111111",
    "SWAB_TEST_BARCODE": "swT11111111",
    "PARTICIPANT_ID": "DHRF-123456789012",
    "TEST_QUESTIONS": "F",
    "COLLEX_OPEN_DATE": "08 Jan 2023",
    "COLLEX_CLOSE_DATE": "28 Jan 2023",
    "FIRST_NAME": "Vinny",
    "WINDOW_START_DATE": "2023-01-08",
    "WINDOW_CLOSE_DATE": "2023-01-28",
    "PORTAL_ID": "1234567",
    "PARTICIPANT_WINDOW_ID": "DHRF-123456789012-001"
  },
  "data": {
    "feedback_text": "Page design feedback",
    "feedback_type": "Page design and structure",
    "feedback_count": "7"
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v2/business/feedback_0_0_1.json
{
  "tx_id": "ea82c224-0f80-41cc-b877-8a7804b56c26",
  "type": "uk.gov.ons.edc.eq:feedback",
  "version": "v2",
  "data_version": "0.0.1",
  "origin": "uk.gov.ons.edc.eq",
  "flushed": false,
  "submitted_at": "2016-05-21T16:37:56.551086",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "collection_exercise_sid": "9ced8dc9-f2f3-49f3-95af-2f3ca0b74ee3",
  "schema_name": "mbs_0001",
  "started_at": "2016-05-21T16:33:30.665144",
  "case_id": "a386b2de-a615-42c8-a0f4-e274f9eb28ee",
  "region_code": "GB-ENG",
  "channel": "RAS",
  "survey_metadata": {
    "survey_id": "009",
    "case_ref": "1000000000000001",
    "case_type": "B",
    "display_address": "ONS, Government Buildings, Cardiff Rd",
    "employment_date": "2021-03-01",
    "form_type": "0253",
    "period_id": "202101",
    "period_str": "January 2021",
    "ref_p_end_date": "2021-06-01",
    "ref_p_start_date": "2021-01-01",
    "ru_name": "ACME T&T Limited",
    "ru_ref": "49900000001A",
    "trad_as": "ACME LTD.",
    "user_id": "64389274239"
  },
  "data": {
    "feedback_text": "Page design feedback",
    "feedback_type": "Page design and structure",
    "feedback_count": "7"
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v2/business/surveyresponse_0_0_3_with_supplementary_data.json
{
  "case_id": "79941c2c-b74e-476c-a80e-e73d62f91fde",
  "tx_id": "43c636bb-975b-4b2f-a5b9-6b696c377c61",
  "type": "uk.gov.ons.edc.eq:surveyresponse",
  "version": "v2",
  "data_version": "0.0.3",
  "origin": "uk.gov.ons.edc.eq",
  "collection_exercise_sid": "41834e4b-ba01-4cb0-9da5-a5da011b8abd",
  "schema_name": "test_supplementary_data",
  "flushed": false,
  "submitted_at": "2023-08-23T08:17:34+00:00",
  "launch_language_code": "en",
  "survey_metadata": {
    "survey_id": "123",
    "form_type": "0253",
    "ru_name": "ESSENTIAL ENTERPRISE LTD.",
    "period_id": "201605",
    "sds_dataset_id": "c067f6de-6d64-42b1-8b02-431a3486c178",
    "user_id": "UNKNOWN",
    "ru_ref": "12346789012A"
  },
  "data": {
    "answers": [
      {
        "answer_id": "same-email-answer",
        "value": "Yes"
      },
      {
        "answer_id": "trading-answer",
        "value": "1947-11-30"
      },
      {
        "answer_id": "sales-bristol-answer",
        "value": 12345
      },
      {
        "answer_id": "sales-london-answer",
        "value": 98765
      },
      {
        "answer_id": "list-collector-employees-answer",
        "value": "No"
      },
      {
        "answer_id": "any-additional-employee-answer",
        "value": "Yes"
      },
      {
        "answer_id": "employee-first-name",
        "value": "John",
        "list_item_id": "UqlQQY"
      },
      {
        "answer_id": "employee-last-name",
        "value": "Doe",
        "list_item_id": "UqlQQY"
      },
      {
        "answer_id": "employee-first-name",
        "value": "Jane",
        "list_item_id": "zfqCLS"
      },
      {
        "answer_id": "employee-last-name",
        "value": "Smith",
        "list_item_id": "zfqCLS"
      },
      {
        "answer_id": "list-collector-additional-answer",
        "value": "No"
      },
      {
        "answer_id": "employment-start",
        "value": "2000-11-30",
        "list_item_id": "zPDHbT"
      },
      {
        "answer_id": "additional-employment-start",
        "value": "2000-11-30",
        "list_item_id": "UqlQQY"
      },
      {
        "answer_id": "additional-employment-start",
        "value": "2000-11-30",
        "list_item_id": "zfqCLS"
      },
      {
        "answer_id": "list-collector-products-answer",
        "value": "No"
      },
      {
        "answer_id": "product-sales-answer",
        "value": 20,
        "list_item_id": "ywFBww"
      },
      {
        "answer_id": "product-sales-answer",
        "value": 30,
        "list_item_id": "XtjjTB"
      }
    ],
    "lists": [
      {
        "items": ["ywFBww", "XtjjTB"],
        "name": "products",
        "supplementary_data_mapping": {
          "89929001": "ywFBww",
          "202346331": "XtjjTB"
        }
      },
      {
        "items": ["zPDHbT"],
        "name": "employees",
        "supplementary_data_mapping": {
          "429001": "zPDHbT"
        }
      },
      {
        "items": ["UqlQQY", "zfqCLS"],
        "name": "additional-employees"
      }
    ],
    "supplementary_data": {
      "schema_version": "v1",
      "items": {
        "products": [
          {
            "identifier": "89929001",
            "guidance_exclude": {
              "title": "Exclude",
              "list": [
                "sports holdalls, gloves, clothing of textile materials, footwear, protective eyewear, rackets, balls, skates",
                "for skiing, water sports, golf, fishing', for skiing, water sports, golf, fishing, table tennis, PE, gymnastics, athletics"
              ]
            },
            "total_volume": {
              "answer_code": "89929005",
              "label": "Total volume produced",
              "unit_label": "Tonnes"
            },
            "guidance_include": {
              "title": "Include",
              "list": [
                "for children's playgrounds",
                "swimming pools and paddling pools"
              ]
            },
            "cn_codes": "2504 + 250610 + 2512 + 2519 + 2524",
            "value_sales": {
              "answer_code": "89929001",
              "label": "Value of sales"
            },
            "name": "Articles and equipment for sports or outdoor games",
            "volume_sales": {
              "answer_code": "89929002",
              "label": "Volume of sales",
              "unit_label": "Tonnes"
            }
          },
          {
            "identifier": "202346331",
            "total_volume": {
              "answer_code": "20234633103",
              "label": "Total volume produced",
              "unit_label": "Kilogram"
            },
            "guidance_include": {
              "title": "Include",
              "list": ["pots and pans", "chopping board"]
            },
            "cn_codes": "1028 + 5908 + 5910 + 591110 + 591120",
            "value_sales": {
              "answer_code": "20234633101",
              "label": "Value of sales"
            },
            "name": "Kitchen Equipment",
            "volume_sales": {
              "answer_code": "20234633102",
              "label": "Volume of sales",
              "unit_label": "Kilogram"
            }
          }
        ],
        "employees": [
          {
            "identifier": "429001",
            "personal_details": {
              "forename": "Henry",
              "surname": "Green",
              "address": {
                "postcode": "BS1 1AJ",
                "house_number": "12",
                "city": "Bristol"
              }
            },
            "employment_details": {
              "job_title": "Customer assistant",
              "start_date": "2020-01-01",
              "salary": {
                "payroll_number": "54345",
                "value": "25000",
                "currency": "GBP"
              }
            }
          }
        ]
      },
      "identifier": "12346789012A",
      "total_uk_sales": 555000.0,
      "note": {
        "title": "Value of total sales",
        "description": "Total value of goods sold during the period of the return",
        "example": {
          "title": "Including",
          "description": "Sales across all UK stores"
        }
      },
      "company_details": {
        "telephone_number": "01171231231",
        "email": "contact@tesco.org"
      },
      "company_name": "Tesco",
      "guidance": "Some supplementary guidance about the survey",
      "incorporation_date": "1947-11-27"
    }
  },
  "started_at": "2023-08-23T08:06:27.801995+00:00",
  "submission_language_code": "en"
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v2/adhoc/surveyresponse_0_0_3.json
{
  "tx_id": "ea82c224-0f80-41cc-b877-8a7804b56c26",
  "type": "uk.gov.ons.edc.eq:surveyresponse",
  "version": "v2",
  "data_version": "0.0.3",
  "origin": "uk.gov.ons.edc.eq",
  "flushed": false,
  "submitted_at": "2016-05-21T16:37:56.551086",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "collection_exercise_sid": "9ced8dc9-f2f3-49f3-95af-2f3ca0b74ee3",
  "schema_name": "mbs_0001",
  "started_at": "2016-05-21T16:33:30.665144",
  "case_id": "a386b2de-a615-42c8-a0f4-e274f9eb28ee",
  "region_code": "GB-ENG",
  "channel": "RH",
  "survey_metadata": {
    "survey_id": "009",
    "case_ref": "1000000000000001",
    "questionnaire_id": "0130000000000300"
  },
  "data": {
    "answers": [
      {
        "answer_id": "first-name",
        "value": "John",
        "list_item_id": "zGBdpb"
      },
      {
        "answer_id": "last-name",
        "value": "Doe",
        "list_item_id": "zGBdpb"
      },
      {
        "answer_id": "first-name",
        "value": "Marie",
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "last-name",
        "value": "Doe",
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "anyone-else",
        "value": "No"
      },
      {
        "answer_id": "number-of-bedrooms-answer",
        "value": 4
      },
      {
        "answer_id": "date-of-birth-answer",
        "value": "1990-01-01",
        "list_item_id": "EINoLs"
      },
      {
        "answer_id": "internet-answer",
        "value": [
          "Broadband or WiFi",
          "A mobile phone network such as 3G, 4G or 5G",
          "Public WiFi hotspot"
        ]
      },
      {
        "answer_id": "business-type-answer",
        "value": "Enter Business type here!",
        "list_item_id": "EINoLs"
      },
      {
        "answer_id": "relationship-answer",
        "value": [
          {
            "list_item_id": "zGBdpb",
            "to_list_item_id": "cWGwcF",
            "relationship": "Husband or Wife"
          },
          {
            "list_item_id": "nEMpwe",
            "to_list_item_id": "adNCSi",
            "relationship": "Son or daughter"
          },
          {
            "list_item_id": "ukGiCK",
            "to_list_item_id": "adNCSi",
            "relationship": "Mother or father"
          }
        ]
      },
      {
        "answer_id": "other-address-uk-answer",
        "value": {
          "line1": "Address Line 1",
          "town": "Town",
          "postcode": "NP10 8XG",
          "uprn": "12345678912"
        },
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "checkbox-answer",
        "value": ["Checkbox 1", "Checkbox 2"]
      },
      {
        "answer_id": "duration-answer",
        "value": {
          "years": 1,
          "months": 2
        }
      }
    ],
    "lists": [
      {
        "items": ["zGBdpb", "cWGwcF"],
        "name": "people"
      }
    ]
  }
}

=== ONSdigital/ons-schema-definitions/examples/eq_runner_to_downstream/payload_v2/adhoc/surveyresponse_0_0_3_with_answer_codes.json
{
  "tx_id": "ea82c224-0f80-41cc-b877-8a7804b56c26",
  "type": "uk.gov.ons.edc.eq:surveyresponse",
  "version": "v2",
  "data_version": "0.0.3",
  "origin": "uk.gov.ons.edc.eq",
  "flushed": false,
  "submitted_at": "2016-05-21T16:37:56.551086",
  "launch_language_code": "en",
  "submission_language_code": "en",
  "collection_exercise_sid": "9ced8dc9-f2f3-49f3-95af-2f3ca0b74ee3",
  "schema_name": "mbs_0001",
  "started_at": "2016-05-21T16:33:30.665144",
  "case_id": "a386b2de-a615-42c8-a0f4-e274f9eb28ee",
  "region_code": "GB-ENG",
  "channel": "RH",
  "survey_metadata": {
    "survey_id": "009",
    "case_ref": "1000000000000001",
    "qid": "0130000000000300",
    "BLOOD_TEST_BARCODE": "BLT11111111",
    "SWAB_TEST_BARCODE": "swT11111111",
    "PARTICIPANT_ID": "DHRF-123456789012",
    "TEST_QUESTIONS": "F",
    "COLLEX_OPEN_DATE": "08 Jan 2023",
    "COLLEX_CLOSE_DATE": "28 Jan 2023",
    "FIRST_NAME": "Vinny",
    "WINDOW_START_DATE": "2023-01-08",
    "WINDOW_CLOSE_DATE": "2023-01-28",
    "PORTAL_ID": "1234567",
    "PARTICIPANT_WINDOW_ID": "DHRF-123456789012-001"
  },
  "data": {
    "answer_codes": [
      {
        "answer_id": "first-name",
        "code": "1"
      },
      {
        "answer_id": "last-name",
        "code": "2"
      },
      {
        "answer_id": "anyone-else",
        "code": "3"
      },
      {
        "answer_id": "number-of-bedrooms-answer",
        "code": "4"
      },
      {
        "answer_id": "date-of-birth-answer",
        "code": "5"
      },
      {
        "answer_id": "internet-answer",
        "answer_value": "Broadband or WiFi",
        "code": "6a"
      },
      {
        "answer_id": "internet-answer",
        "answer_value": "A mobile phone network such as 3G, 4G or 5G",
        "code": "6b"
      },
      {
        "answer_id": "internet-answer",
        "answer_value": "Public WiFi hotspot",
        "code": "6c"
      },
      {
        "answer_id": "business-type-answer",
        "code": "7"
      },
      {
        "answer_id": "relationship-answer",
        "code": "8"
      },
      {
        "answer_id": "other-address-uk-answer",
        "code": "9"
      },
      {
        "answer_id": "checkbox-answer",
        "answer_value": "Checkbox 1",
        "code": "10a"
      },
      {
        "answer_id": "checkbox-answer",
        "answer_value": "Checkbox 2",
        "code": "10b"
      },
      {
        "answer_id": "checkbox-answer",
        "answer_value": "Checkbox 3 (this is sent but doesn't have to exist in data.answers)",
        "code": "10c"
      },
      {
        "answer_id": "duration-answer",
        "code": "11"
      }
    ],
    "answers": [
      {
        "answer_id": "first-name",
        "value": "John",
        "list_item_id": "zGBdpb"
      },
      {
        "answer_id": "last-name",
        "value": "Doe",
        "list_item_id": "zGBdpb"
      },
      {
        "answer_id": "first-name",
        "value": "Marie",
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "last-name",
        "value": "Doe",
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "anyone-else",
        "value": "No"
      },
      {
        "answer_id": "number-of-bedrooms-answer",
        "value": 4
      },
      {
        "answer_id": "date-of-birth-answer",
        "value": "1990-01-01",
        "list_item_id": "EINoLs"
      },
      {
        "answer_id": "internet-answer",
        "value": [
          "Broadband or WiFi",
          "A mobile phone network such as 3G, 4G or 5G",
          "Public WiFi hotspot"
        ]
      },
      {
        "answer_id": "business-type-answer",
        "value": "Enter Business type here!",
        "list_item_id": "EINoLs"
      },
      {
        "answer_id": "relationship-answer",
        "value": [
          {
            "list_item_id": "zGBdpb",
            "to_list_item_id": "cWGwcF",
            "relationship": "Husband or Wife"
          },
          {
            "list_item_id": "nEMpwe",
            "to_list_item_id": "adNCSi",
            "relationship": "Son or daughter"
          },
          {
            "list_item_id": "ukGiCK",
            "to_list_item_id": "adNCSi",
            "relationship": "Mother or father"
          }
        ]
      },
      {
        "answer_id": "other-address-uk-answer",
        "value": {
          "line1": "Address Line 1",
          "town": "Town",
          "postcode": "NP10 8XG",
          "uprn": "12345678912"
        },
        "list_item_id": "cWGwcF"
      },
      {
        "answer_id": "checkbox-answer",
        "value": ["Checkbox 1", "Checkbox 2"]
      },
      {
        "answer_id": "duration-answer",
        "value": {
          "years": 1,
          "months": 2
        }
      }
    ],
    "lists": [
      {
        "items": ["zGBdpb", "cWGwcF"],
        "name": "people"
      }
    ]
  }
}
